development:
  adapter: postgresql
  encoding: utf8
  database: dwidder_development
  pool: 5
  username: 
  password:

test: 
  adapter: postgresql
  encoding: utf8
  database: dwidder_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: dwidder_production
  pool: 5
  username: 
  password: